format:
  html:
    toc: true
    number-sections: false

execute:
  echo: false          # keep hiding code
  freeze: auto         # still reuse cache on subsequent builds

# _quarto.yml  (root)
project:
  type: website   
  output-dir: docs 

render:
  - notebooks/**/*.ipynb    # any .ipynb under notebooks/