project:
  type: website
  output-dir: docs           # already set
  render:
    - index.qmd              # the new landing page
    - README.md              # (optional) keep original too
    - notebooks/**/*.ipynb   # your two notebooks
    - "*.md"                 # any extra markdown files

format:
  html:
    toc: true
    number-sections: false
    self-contained: true

website:
  title: "Home Credit Default Risk"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Notebooks
        menu:
          - text: Sample (small)
            file: notebooks/01_homecredit_sample.ipynb
          - text: Full (big)
            file: notebooks/02_homecredit_full.ipynb
      - text: Docs
        menu:
          - README.md         # or any other .md / .qmd
  sidebar:                    # optional floating sidebar
    style: "floating"
    collapse-level: 2
    contents:
      - section: "Notebooks"
        contents: notebooks/*
      - section: "Docs"
        contents:
          - README.md
