project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    number-sections: false
    self-contained: true
    code-tools: true           
    code-fold: true            
    code-summary: "Code"       
    echo: true                 

profiles:
  dev:
    project:
      output-dir: docs-dev
    format:
      html:
        toc: true
        number-sections: false
        self-contained: true
        code-tools: true
        code-fold: true      
        echo: true

execute:
  freeze: auto

website:
  title: "Home Credit Default Risk Analysis"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Notebooks
        menu:
          - notebooks/01_homecredit_sample.ipynb
          - notebooks/02_homecredit_full.ipynb
      - text: Docs
        menu:
          - reports/EDA_Report.md
          - reports/Feature_Engineering_Notes.md
          - reports/Final_Report.md
  sidebar:
    collapse-level: 2
    style: floating
    contents:
      - notebooks/01_homecredit_sample.ipynb
      - notebooks/02_homecredit_full.ipynb
      - reports/EDA_Report.md
      - reports/Feature_Engineering_Notes.md
      - reports/Final_Report.md
