project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - notebooks/*.ipynb
    - docs/*.md           # any extra markdown

format:
  html:
    toc: true
    number-sections: false
    self-contained: true
    code-tools: true        # adds “Show code / Hide code”
    echo: false             # hide code by default (PUBLIC)

# ---------- dev version ----------
profiles:
  dev:
    format:
      html:
        toc: true
        number-sections: false
        self-contained: true
        code-tools: true
        echo: true          # show code (DEV)
        output-dir: docs-dev

execute:
  freeze: auto            # skip execution unless notebooks change

website:
  title: "Home Credit Default Risk"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Notebooks
        menu:
          - notebooks/01_homecredit_sample.ipynb
          - notebooks/02_homecredit_full.ipynb
      - text: Docs
        menu:
          - docs/credit_scoring_project.md
  sidebar:
    collapse-level: 2
    style: floating
    contents:
      - section: "Notebooks"
        contents: notebooks/*
      - section: "Docs"
        contents: docs/*
